### ISSUE TITLE
SUSEConnect cli feedback

### ISSUE THREAD

**Issue by kalabiyau** [jsrain/zypper-search-packages#2]
Hi, Jiri. Just did the following testing of the package search implementation for zypper:

> docker run -ti --rm <omitted>/suse/sles15:ga-rc1
> zypper ar <omitted>/SUSE:/SLE-15:/GA/standard/ 15
> zypper in zypper-package-search-plugin
> zypper package-search vim

got :

> bash-4.4# zypper package-search vim
> Following packages were found in following modules:
> 
> gvim: Desktop Applications Module
> texlive-context-vim: Desktop Applications Module
> vim: Basesystem Module
> vim-data: Basesystem Module
> vim-data-common: Basesystem Module
> vim-plugin-conky: Desktop Applications Module
> vim-plugin-devhelp: Development Tools Module
> 
> To activate respective module or product, use SUSEConnect --product.
> Use SUSEConnect --help for more details.
> 
> bash-4.4# SUSEConnect --product
> Please provide a product identifier

I hope you are open for the feedback:

We see that here customer is offered to use SUSEConnect

We actually can help customer even more by providing relevant commands for the SUSEConnect.
That information is already in the output of the `SUSE::Connect::PackageSearch.search('vim')`

E.g. for vim it would be couple of options like:

`SUSEConnect -p sle-module-development-tools/15/x86_64` as it stated in the output - `requires_registration => false`

So, I think it will much more useful for the customer to receive a precise SUSEConnect command.

So - you miss this package - use this command and install

**Comment by kalabiyau** [comment]
@jsrain any opinion on that?

**Comment by jsrain** [comment]
Sorry I took that much time ... merged the PR from Thomas, thanks for that!
